### ISSUE TITLE
React Native: Unknown option: <project>/node_modules/redux-recycle/.babelrc.stage

### ISSUE THREAD

**Issue by tomkur** [omnidan/redux-recycle#3]
Happens during transformation by React Native packager, more specifically:
```
Error while persisting cache: TransformError: <project>/node_modules/redux-recycle/lib/index.js: [BABEL] <project>/node_modules/redux-recycle/lib/index.js: Unknown option: <project>/node_modules/redux-recycle/.babelrc.stage
```

This is probably due to RN 0.16 and higher using Babel 6 where stage option [was replaced](https://babeljs.io/blog/2015/10/31/setting-up-babel-6).

**Comment by omnidan** [comment]
@tomkur would you mind doing a PR for this? :grin: If not I'll try to have a look at it tomorrow :wink:

**Comment by steida** [comment]
@tomkur To the rescue https://github.com/este/este/blob/b3ae148ee5d65a1c86770b6d77fd5685594913cf/gulpfile.babel.js#L149

**Comment by tomkur** [comment]
@omnidan by following link provided by @steida I've noticed (this thread)[https://github.com/facebook/react-native/issues/4062#issuecomment-164598155], so it seems it's a bigger problem and I'm not sure what's the appropriate solution here.

@steida thanks for the workaround!

**Comment by omnidan** [comment]
@tomkur I just think `.babelrc` needs to be updated - it's [already done in redux-undo](https://github.com/omnidan/redux-undo/commit/7985ee4f120e8aff492cfbf53f699af1868992ee)
