### ISSUE TITLE
Discussion: Implementing more complex re-initialization behavior

### ISSUE THREAD

**Issue by steida** [omnidan/redux-recycle#4]
Btw http://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store/35641992#35641992

Sometime we need reuse initialState, sometimes currentApp state (for https://github.com/reactjs/react-router-redux for example)

This is just inform issue, to be discussed.

**Comment by steida** [comment]
https://github.com/este/este/blob/0af0e5c826d850514441c12244670bd8636f3d30/src/common/configureStore.js#L87

**Comment by omnidan** [comment]
@steida how is it hard to make reusable? You can use this reducer instead of writing your own, just like described in the stackoverflow post. It will send a `@@redux-recycle/INIT` action and `undefined` state (unless you define your own as a third argument)

**Comment by steida** [comment]
Check usage in Este, sometimes we need initialState, sometimes current state. https://github.com/este/este/blob/0af0e5c826d850514441c12244670bd8636f3d30/src/common/configureStore.js#L92

**Comment by omnidan** [comment]
@steida I see, well in this case you need to write your own higher-order reducer, redux-recycle is just a small utility function to re-initialize the state on an action :wink:

I'll leave this open for discussion, though.

**Comment by steida** [comment]
I agree, I just want to write somewhere 😅  that sure you can use this for an inspiration only ;)

**Comment by ArikMaor** [comment]
I think the ability to run a reducer to reset could be useful and a good fit here
I've implemented it in #5
comments are appreciated

**Comment by omnidan** [comment]
resolved through #5
